version: "3.7"

services:
  app:
    # image: garampark/php-7-fpm-nginx:0.0.2
    build:
      context: ./.docker
    volumes:
      - ./public:/var/www/app/public
      - ./default.conf:/etc/nginx/sites-enabled/default
    ports:
      - 80:80
